### ISSUE TITLE
Ranger tracking the Tracker

### ISSUE THREAD

**Issue by peteralewis** [TopShelfCraft/Tracker#3]
Hi Michael,

Just to confirm, this plugin only calls your personal website for install/uninstall/updates of the Tracker plugin, for I assume, a log of usage? Currently it looks like it's not passing any data from the site it's installed on, but I'm assuming this could change in the future, as Ranger already accepts a second parameter?

**Comment by michaelrog** [comment]
Howdy @peteralewis — You're correct: The "Ranger" component records install/uninstall/update events. It uses the exact same methods and info as Craft's own updater/licensing API.

(For the moment, this isn't actually "recording" anything — i.e. the Top Shelf Craft server isn't "turned on" yet — but eventually it'll help me keep track of active versions, mostly to aid with support and release planning.)
